---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-api-{{FEATURE_BRANCH_NAME}}
  labels:
    app: {{APP_NAME}}-api-{{FEATURE_BRANCH_NAME}}
spec:
  selector:
    app: {{APP_NAME}}-api-{{FEATURE_BRANCH_NAME}}
  ports:
    - name: http
      protocol: TCP
      port: {{SERVICE_PORT}}  # e.g., 80
      targetPort: {{APP_CONTAINER_PORT}}  # e.g., 8003
    - name: http-metrics
      protocol: TCP
      port: {{METRICS_SERVICE_PORT}}  # e.g., 8001
      targetPort: {{METRICS_CONTAINER_PORT}}  # e.g., 8001
  type: {{SERVICE_TYPE}}  # e.g., ClusterIP, NodePort, LoadBalancer
